### ISSUE TITLE
Typical hardware setup for LISFLOOD

### ISSUE THREAD

**Issue by folmerkrikken** [ec-jrc/lisflood-code#116]
Hello,

I am thinking of using LISFLOOD to create global future flood risk at a 0.1degree resolution, but I am wondering what a typical hardware setup is needed for such an exercise. How much memory / CPU's are typically needed to get reasonable running times.

Thanks in advance,
Folmer Krikken

**Comment by StefaniaGrimaldi** [comment]
Dear @folmerkrikken,

thank you for your enquiry.

We can share our experience: we run LISFLOOD-OS for the global domain on the JRC HPC infrastructure (Intel(R) Xeon(R) CPU E5-2609 v4 @ 1.70GHz).

One year of global run with 0.05 degrees resolution using 1 core takes 18 hours with peak of memory usage of 37 Gigabytes.
This simulation only wrote time series files and end-maps. The computational time increases when printing a large number of output maps.

The pieces of information above refer to 0.05 degrees resolution because this is the resolution of the latest global set up (https://data.jrc.ec.europa.eu/dataset/f96b7a19-0133-4105-a879-0536991ca9c5; https://confluence.ecmwf.int/display/CEMS/GloFAS+v4.0+hydrological+reanalysis)

Have you already prepared all the LISFLOOD-OS input maps with 0.1 degrees resolution? The description of the LISFLOOD-OS input maps is available here https://ec-jrc.github.io/lisflood-code/3_step4_preparing-input-files/; https://ec-jrc.github.io/lisflood-code/4_Static-Maps-introduction/

GloFAS 3.3 (current operational version) has 0.1 degrees spatial resolution. The next major GloFAS upgrade (operational in 2023) has 0.05 degrees resolution. This objective required the preparation of 0.05 degrees resolution input maps. We are working on a paper to present the datasets; the datasets will be publicly available following the publication of the paper.
Nevertheless, it is strongly recommended to use the 0.05 degrees dataset. The 0.05 degrees dataset benefits of the most recent research findings and remote-sensing and in-situ database (the paper will explain all the details).
Moroever, we will maintiain the 0.05 degrees dataset only.

We hope that our answer helps,

Carlo Russo, Stefania Grimaldi (on behalf of the LISFLOOD-OS team)
