### ISSUE TITLE
Problem with the lisflood use case LF_ETRS89_UseCase

### ISSUE THREAD

**Issue by 12530** [ec-jrc/lisflood-code#120]
Hi, 
I am very new to lisflood. After following the instruction of installation using docker image, I cannot run the first use case successfully. It complains about 'uzf'. Below I copy the error details. 

$ docker run -v /mnt/d/lisflood/test/LF_ETRS89_UseCase:/input jrce1/lisflood /input/settings/cold.xml
Traceback (most recent call last):
  File "/lisf1.py", line 34, in <module>
    sys.exit(main())
  File "/lisflood/main.py", line 222, in main
    lisfloodexe(lissettings)
  File "/lisflood/main.py", line 155, in lisfloodexe
    model_to_run.run()
  File "/lisflood/global_modules/zusatz.py", line 139, in run
    self._runDynamic()
  File "/opt/conda/envs/lisflood/lib/python3.7/site-packages/pcraster/framework/frameworkBase.py", line 371, in _runDynamic
    self._userModel().dynamic()
  File "/lisflood/Lisflood_dynamic.py", line 241, in dynamic
    self.output_module.dynamic()
  File "/lisflood/global_modules/output.py", line 261, in dynamic
    reportStartDate, reportStepStart, reportStepEnd, frequency)
  File "/lisflood/global_modules/netcdf.py", line 506, in writenet
    nf1.variables[var_name][flag, :, :] = map_np
KeyError: 'uzf'

ERROR conda.cli.main_run:execute(49): `conda run python /lisf1.py /input/settings/cold.xml` failed. (See above for error)
LisfloodPy  4.1.1   09/06/2022

Moreover, how to test the second case? It is not described in the note. Any help is appreciated. 
Thanks, Liguang

**Comment by doc78** [comment]
Dear Liguang
Can you please provide further info about your test? Have you changed anything in the xml file?
I just did the test using the following instructions and it works:

docker pull jrce1/lisflood:latest
docker run -v /home/carlo/docker_test:/usecases jrce1/lisflood usecases
docker run -v /home/carlo/docker_test/LF_ETRS89_UseCase:/input jrce1/lisflood /input/settings/cold.xml

Maybe you can attach your cold.xml file, so I will give it a look.
To run the second case, you can use the following command:

docker run -v /home/carlo/docker_test/LF_lat_lon_UseCase:/input jrce1/lisflood /input/run_lat_lon.xml

(replace "/home/carlo/docker_test" with your path)
Please try and let me know if it works for you
Thanks
Carlo

**Comment by doc78** [comment]
The error means that for some reason lisflood could not create the variable uzf in the NetCDF file. You can try to change the following line 2859 in your cold.xml file:

`<textvar name="UZForestState" value="$(PathOut)/uzf">`

into 

`<textvar name="UZForestState" value="$(PathOut)/uzfstate">`

Please let me know if you still get the error message. Can you please sent me also further info about the HW and the Operating System you are using? 
Regarding the output of the run_lat_lon.xml, you will find the output in the "reference" folder, as stated in the log message:

[X] The simulation output as specified in the settings file can be found in /input/reference

The reference folder contains already some reference files, but when you run lisflood it will add 2 new output files: chanqWin.tss and dis_run.tss. You can also change your output folder by selecting a different value in the PathOut variable of the xml file, if you want.

Thanks
Carlo

**Comment by 12530** [comment]
Hello Carlo,
After changing the uzfstate, it works now. But these should be two different state variables? It is strange that the same version works for you. 

I am using MS 11 Pro (10.0.22000 Build 22000) with the built-in WSL (Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC))), deployed with Ubuntu 20.04.5 LTS. 
Below are some info about the hardware. 
     *-memory: 65536 MB RAM
     *-cpu product: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 CPUs)

Thank you for your help.
Liguang

**Comment by doc78** [comment]
I think the problem is that in the cold.xml file there are two variables using a similar name "uzf" and "uzF":

line 2859: `<textvar name="UZForestState" value="$(PathOut)/uzf">`
line 3358: `<textvar name="UZForestMaps" value="$(PathOut)/uzF">`

so that on microsoft-based operating systems the filename is not case sensitive, and thus there is a problem on writing the output using the same filename for two variables. Changing one of the names into "uzfstate" solved the problem, because now you will have two distinct filename as output maps. In Linux operating system this is not an issue, since on Linux filenames are case sensitive.
Please note that in general we are not giving support for microsoft windows based platforms, since we use Linux native operating systems in all our developments and tests. As you can see, even if in theory the WSL is a Linux system, sometimes these small differences can create issues. So I suggest to switch, when possible, to a real Linux operating systems, or even a Virtual Machine running Linux, instead of WSL.

**Comment by 12530** [comment]
Thank you very much. It seems better to switch to a Linux native system.
