### ISSUE TITLE
Issues related to startup

### ISSUE THREAD

**Issue by WWWkingMMM** [ec-jrc/lisflood-code#128]
Sorry to bother you again
I use the following code：./main.py -v beach_adaptive_hf.par
Although the program does not report any errors, there are no prompts on the interface. Is this a program issue or a par file issue?

**Comment by doc78** [comment]
If you are using the python source code, please try the following syntax for the lisflood command, from the lisflood-code main folder:

python lisfl1.py <your_setting_file.xml> -v

Otherwise, if you installed the lisflood-model pip package, you can run the command:

lisflood <your_setting_file.xml> -v

Please note that the -v (--veryquiet) means that no output will be written in stdout, so you will get directly the discharge data in the PathOut folder of you settings file but not progess info will be shown. If you want to see the progress steps of the model, just run the command:

lisflood <your_setting_file.xml> 

Carlo

**Comment by WWWkingMMM** [comment]
I tried the following code:
lisflood <your_setting_file.xml>
It can work. Does that mean that the input file needs to be made into XML format? How can I input a par file.

Kind regards,
Allen

**Comment by StefaniaGrimaldi** [comment]
Dear Allen,

LISFLOO OS rainfall-runoff model takes as input exclusively files in .xml format. There is no .par file in LISFLOOD OS.

You can find the description of the settings .xml file here https://ec-jrc.github.io/lisflood-code/2_ESSENTIAL_setting-file/, https://ec-jrc.github.io/lisflood-code/3_step3_preparing-setting-file/ 

Moreover, a template of the settings .xml file is available from https://github.com/ec-jrc/lisflood-code/blob/master/src/lisfloodSettings_reference.xml

The settings .xml file allows you to define the temporal and spatial domain of your simulation, the meteorological inputs, and the static maps. Moreover, you will be able to select the hydrological processes that are relevant for your study area. A complete documentation about the code is available here https://ec-jrc.github.io/lisflood-model/ 

Kind regards,
Stefania
