### ISSUE TITLE
Time parsing error using pandas 2.0

### ISSUE THREAD

**Issue by emiliano-gelati** [ec-jrc/lisflood-code#130]
Using pandas 2.0, I get the following error in [`global_modules/settings.py`, line 619](https://github.com/ec-jrc/lisflood-code/blob/master/src/lisflood/global_modules/settings.py#L619):

`AttributeError: module 'pandas._libs.tslibs.parsing' has no attribute 'parse_time_string'`

Here is a proposal to fix this using [pandas.to_datetime](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html): https://github.com/GeoscienceUiO/lisflood-code_UiO/commit/9de2c0f18a1a34cd985ada0596fd793ac22d5811
However, the function is available starting from pandas 1.0, so it would not be compatible with the current requirement [pandas >= 0.25.1](https://github.com/ec-jrc/lisflood-code/blob/master/requirements.txt#L21).

I could open a pull request if it is of interest.

**Comment by doc78** [comment]
Dear Emiliano

Thanks for sharing your fix. Yes, we are aware that the function was renamed recently and now is called "parse_datetime_string_with_reso" staring from pandas version 2.
Indeed, instead of changing the call, your fix will be better since will be compatible starting from pandas version 1, that should be OK in  most cases.
I will update the code and requirements, thanks!

Carlo

**Comment by doc78** [comment]
Fixed in v4.1.3
