### ISSUE TITLE
issue installing via pip in mac osx arm64

### ISSUE THREAD

**Issue by felipearrospide** [ec-jrc/lisflood-code#139]
Greetings,

Im on a MacBook Air, M2 chip
I have an issue when trying to install lisflood via conda + pip:

conda create -n lisflood
conda activate lisflood
conda install -c conda-forge pcraster
pip install lisflood-model

the error is the following:
creating build/temp.macosx-11.0-arm64-cpython-38/src/lisflood/hydrological_modules
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/felipearrospide/mambaforge/envs/lisflood/include -arch arm64 -fPIC -O2 -isystem /Users/felipearrospide/mambaforge/envs/lisflood/include -arch arm64 -stdlib=libc++ -I/opt/homebrew/opt/llvm/include -I/Users/felipearrospide/mambaforge/envs/lisflood/include/python3.8 -c src/lisflood/hydrological_modules/kinematic_wave_parallel_tools.c -o build/temp.macosx-11.0-arm64-cpython-38/src/lisflood/hydrological_modules/kinematic_wave_parallel_tools.o -O3 -march=native -fopenmp
      clang: error: unsupported option '-fopenmp'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

from what I understand, there is an issue with the C compiler that apparently does not recognize the flag "-fopenmp"
Has anyone else encountered an issue like this?

I have used lisflood via Docker but this time I would like to install the model without the need for Docker

**Comment by faarrosp** [comment]
I'll answer myself :D after a lot of trial and error, this solved the problem:

reminder: using a 2023 MacBook Air with M2 Chip, z shell (zsh), mambaforge installed

1st follow the steps as pointed out in the documentation:

- create an environment using conda
- install python version 3.8 and pcraster using conda install or mamba install with conda-forge channel
- try then using pip install lisflood-model

2nd if this fails because of clang:
- install llvm by typing brew install llvm
- please note that by the end of the installation, the installer tells you that you need to explicitly change the environment variables so that compilers can find llvm:

If you need to have llvm first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"

do as instructed. If you miss the message, dont panic, type brew info llvm and copy the instructions for exporting the new environment variables

- restart your shell or open a new terminal window
- activate the environment and try pip install lisflood-model again, for me it ran smoothly


now you can try the usecases which by the way, if you followed these steps, you will need one final step, which is downgrading numexpr to the 2.8.1 version (see related issue) by typing pip install numexpr==2.8.1 

finally you should be ready to go
