### ISSUE TITLE
Problems to run the Lisflood test case Drina

### ISSUE THREAD

**Issue by salampe** [ec-jrc/lisflood-code#14]
Email received by Marcio (CEMADEN):

We found some problems to run the Lisflood. Please check the print screen attached.

My best wishes,

Marcio.

![testliflood](https://user-images.githubusercontent.com/28801397/58337623-7a872b00-7e46-11e9-8a98-8bd3f14b193c.PNG)

**Comment by emiliano-gelati** [comment]
The error may be caused by an outdated version of [pandas](https://pandas.pydata.org/)
LISFLOOD works fine with the latest version (currently [0.24.2](https://github.com/pandas-dev/pandas/releases/tag/v0.24.2))

**Comment by domeniconappo** [comment]
I think it's the case to include some more instructions in docs about how to create a virtualenv from scratch. 
And also it's better to define a minimum version required for pandas in requirements.txt and setup.py, because if user uses an existing environment with an old pandas version, pip tool just says "pandas  already installed". 
So it will be `pandas>=0.24.2` instead of just `pandas'.
I will take care of it.

Meanwhile solution is `pip install -U pandas` or `pip install "pandas>=0.24.2"`

**Comment by salampe** [comment]
@domeniconappo can this issue be closed?

**Comment by domeniconappo** [comment]
@salampe 
the problem was due an existing older pandas version. We addressed this by specifying the minimum required version for pandas.

we didn't receive further feedback from this user
