### ISSUE TITLE
Inquiry on Data Assimilation

### ISSUE THREAD

**Issue by KumaGIS** [ec-jrc/lisflood-code#150]
I hope this message finds you well. My name is Madhawa, and I am currently engaged in hydrological research focused distributed hydrological modeling in a large basin in Sri Lanka.  My question is more general rather than technical.
My primary interest lies in the domain of streamflow data assimilation, particularly utilizing the capabilities of the LISFLOOD model to enhance our understanding and management of water resources in the region.  According to the literature, this model was mainly applied in European basins. Can we use this model for hydrological simulations outside the Europe like in Asia?

Furthermore, During my exploration of the LISFLOOD model, I noticed that there is a distinct file dedicated to the Ensemble Kalman Filter, which I believe could significantly contribute to the accuracy and efficiency of streamflow predictions in my study area. Given the complexity and potential of this approach, I am eager to delve deeper into the mechanics of data assimilation within the LISFLOOD framework.

To this end, I am reaching out to inquire if there are any available resources, such as documentation, user guides, or sample code exercises, specifically tailored to understanding and implementing data assimilation techniques, like the Ensemble Kalman Filter, within the LISFLOOD model. Access to such materials would be immensely beneficial, not only for facilitating a smoother application process but also for ensuring the robustness and reliability of the model outputs in my research.

Thank you for your time and consideration. I look forward to your response and any assistance you can offer in this regard.

**Comment by StefaniaGrimaldi** [comment]
Dear @KumaGIS,

thank you for getting in touch with us, we are pleased to know that you are interested in using OS LISFLOOD for your work.

OS LISFLOOD has been applied to areas outside of Europe. In fact,  OS LISFLOOD is used within the Global Flood Awareness System (GloFAS) of the Copernicus Emergency Management Service: https://www.globalfloods.eu/,  https://confluence.ecmwf.int/display/CEMS/LISFLOOD.
A complete set of OS LISLFOOD implementation maps with 0.05 degrees resolution for the global domain is available for download here: https://data.jrc.ec.europa.eu/dataset/68050d73-9c06-499c-a441-dc5053cb0c86
The LISLFOOD tool  "cutmaps" (https://github.com/ec-jrc/lisflood-utilities) can be used to crop the global maps to the desired area of interest.

The application of the Ensemble Kalman Filter to LISFLOOD is not currently in use. Therefore, we are not able to provide support about that specific application. We are sorry to provide a disappointing answer about the data assimilation routine; we are eager to provide our support for the use of the OS LISFLOOD model, LISVAP, the LISFLOOD utilities, and the LISFLOOD calibration tool.

Kind regards,
Stefania (on behalf of the OS LISFLOOD developers team)

**Comment by KumaGIS** [comment]
Thank you very much for the quick response. I understand the situation regarding the data assimilation part. However, I hope the given code template can be used to develop a DA framework for the LISFLOOD model.

**Comment by KumaGIS** [comment]
Dear @StefaniaGrimaldi ,
I understand that the Ensemble Kalman Filter is not currently implemented in LISFLOOD. Could you please tell me if there are any reference documents from previous model versions that utilized this? Because I am in the process of developing a data assimilation framework with the LISFLOOD model. I have a few doubts and if there is any documentation regarding this it would be helpful. 

I found a few articles that used DA and LISFLOOD.
Article 1 : DOI: [10.5194/hessd-10-13783-2013](http://dx.doi.org/10.5194/hessd-10-13783-2013)
Article 2 : doi: [10.1016/j.jhydrol.2016.10.041](https://doi.org/10.1016%2Fj.jhydrol.2016.10.041)

Looking forward to hearing from you
Thank you.

**Comment by StefaniaGrimaldi** [comment]
Dear @KumaGIS,
 
we would like to recommend the following reference https://www.sciencedirect.com/science/article/pii/S1364815209002643#sec4, in addition to the ones that you have already listed.

Unfortunately, due to project priorities (and the constant struggle with time and resources management!), the data assimilation code has not been maintained since the publication of the paper above. This means that (substantial) edits are required to activate the data assimilation routine with the most updated OS LISFLOOD code. 

Nevertheless, we believe that there is value in such a development, and we are very pleased to know about your work to develop a data assimilation framework with the OS LISFLOOD model. 

Albeit we are not able to provide timely support on the data assimilation routine, we are keen to provide ancillary information and general support for the use of the OS LISFLOOD suite. We hope to be able to slightly facilitate your work. 
Furthermore, we would be pleased if you considered the idea of contributing to the OS LISFLOOD repository. We understand that your work is at the early stages, but it would be great to keep in contact as your work on OS LISFLOOD and DA can benefit the scientific community.

Kind regards,
Stefania (on behalf of the OS LISFLOOD developers team)
