### ISSUE TITLE
Problem when compiling the kinematic wave parallel tools on MacOS

### ISSUE THREAD

**Issue by StefaniaGrimaldi** [ec-jrc/lisflood-code#93]
**MacOS:** The instruction "python compile_kinematic_wave_parallel_tools.py build_ext --inplace" returns the following error message:
"error: unsupported option '-fopenmp'
error: command '/usr/bin/gcc' failed with exit code 1"

**Comment by doc78** [comment]
The following steps helps to install lisflood on MacOS if you are experiencing this issue during the compilation of kinematic wave:
"clang: error: unsupported option '-fopenmp'"

A way to solve the issue is to use gcc version 6. You can install and use it on MacOS (tested on Catalina and Monterey) by following these steps:

- Install brew:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- Install gcc version 6 
brew install gcc@6

- create symbolic link:
ln -s /usr/local/bin/g++-6 /usr/local/bin/gcc

- put /usr/local/bin to the head of the $PATH env variable
export PATH="/usr/local/bin:$PATH"

Now you can run "python compile_kinematic_wave_parallel_tools.py build_ext --inplace" using gcc v6 and it should work. 

This solves also the same issue when trying to install lisflood by Pypi package "pip install lisflood-model", since this package tries to compile kinematic wave with the current MacOS version of gcc and then fails.  
(if you already tried to install lisflood-model, you may have it in your pip cache, so before installing it again you should use the command "pip cache purge" to remove completely previous pip installation, otherwise new installation will not trigger again the compilation of the kinematic wave)
